# when the swarm_manager_operational group is empty, meaning there
# are no hosts running swarm, we need to initialize one of the hosts
# then add it to the swarm_manager_operational group
- hosts: tag_jra_environment_{{ env }}:tag_jra_swarm_node_type_infra_logging
  become: true
  vars:
    swarm_node_host_name: "{{ ec2_private_dns_name | regex_replace('(ip-[0-9]*-[0-9]*-[0-9]*-[0-9]*)\\.[a-zA-Z0-9]*\\.[a-zA-Z0-9]*', '\\1')}}"
  tasks:
    - name: clear existing docker config file for manager leader nodes
      shell: >
       sudo rm -f /etc/systemd/system/docker.service.d/jra-docker-config.conf &&
       sudo mkdir -p /etc/systemd/system/docker.service.d

    - name: write customized docker start config file with labels for manager leader nodes
      shell: >
       sudo bash -c
       'echo "       --log-driver=fluentd
       --log-opt fluentd-address=localhost:8282
       --log-opt labels=jra.swarm-node-name,jra.instance-name,jra.environment,jra.environment-size,jra.environment-type,jra.environment-instance-id,jra.failure-zone,jra.subnet-type,jra.swarm-instance-type,jra.swarm-node-type,jra.swarm-node-type,jra.environment-flip,jra.application-name,jra.container-name,jra.domain-name
       --log-opt tag='docker.\{\{.ID\}\}'"
       >> /etc/systemd/system/docker.service.d/jra-docker-config.conf'
      ignore_errors: yes

    - name: restart docker on manager leader nodes
      shell: >
       sudo systemctl daemon-reload &&
       sudo systemctl restart docker

        