---
# determine the status of each manager node and break them
# into two groups:
#   - swarm_manager_operational (swarm is running and active)
#   - swarm_manager_bootstrap (host needs to be joined to the cluster)
- hosts: tag_jra_environment_{{ env }}:&tag_jra_swarm_instance_type_swarm_manager
  become: true
  tasks:
    - name: determine swarm status
      shell: >
        docker info | egrep '^Swarm: ' | cut -d ' ' -f2
      register: swarm_status

    - name: create swarm_manager_operational group
      add_host:
        hostname: "{{ item }}"
        groups: swarm_manager_operational
      with_items: "{{ ansible_play_hosts | default(play_hosts) }}"
      when: "'active' in hostvars[item].swarm_status.stdout_lines"
      run_once: true

    - name: create swarm_manager_bootstrap group
      add_host:
        hostname: "{{ item }}"
        groups: swarm_manager_bootstrap
      with_items: "{{ ansible_play_hosts | default(play_hosts) }}"
      when: "'active' not in hostvars[item].swarm_status.stdout_lines"
      run_once: true

# Make sure the proper volume mount points are created on the infra-persistence node
- hosts: tag_jra_environment_{{ env }}:&tag_jra_swarm_node_type_infra_persistence
  become: true
  tasks:
    - name: create the jira mysql mount directory if it doesn't already exist
      shell: >
        sudo mkdir -p /usr/local/jra/docker-data-volumes/jra-infra/admin-jira-db/data
      ignore_errors: yes

    - name: make sure the processes running inside containers have access to the directories
      shell: >
        sudo chmod -R 777 /usr/local/jra/docker-data-volumes
      ignore_errors: yes

# Make sure the proper volume mount points are created on all the admin ui web nodes
- hosts: tag_jra_environment_{{ env }}:&tag_jra_swarm_node_type_admin_ui_web
  become: true
  tasks:
    - name: create the jira mount directory if it doesn't already exist
      shell: >
        sudo mkdir -p /usr/local/jra/docker-data-volumes/jra-infra/admin-jira-ui/home
      ignore_errors: yes

    - name: make sure the processes running inside containers have access to the directories
      shell: >
        sudo chmod -R 777 /usr/local/jra/docker-data-volumes
      ignore_errors: yes

# Deploy the Jira Services
- hosts: swarm_manager_operational[0]
  become: true
  tasks:
    - name: create the docker script files directory it doesn't already exist
      shell: >
        sudo mkdir -p /usr/local/jra/scripts/compose/jarch-infra-admin-jira-stacks
      ignore_errors: yes

    - name: copy the stack files
      copy:
        src: "{{ stack_file_dir }}/"
        dest: /usr/local/jra/scripts/compose/jarch-infra-admin-jira-stacks/
  
    - name: deploy jarch-infra-admin-jira stack
      shell: >
        ENV_DOMAIN_PREFIX={{ env_domain_prefix }} docker stack deploy jarch-infra-admin-jira -c {{ stack_file_name }}
      args:
        chdir: /usr/local/jra/scripts/compose/jarch-infra-admin-jira-stacks/

