version: '3'

services:
 
  proxy-traefik:
    image: traefik:v1.4.2
    ports:
      - 81:80
      - 8188:8080
    networks:
      - proxy-traefik-network
    command:
      - --docker
      - --docker.swarmmode
      - --docker.domain=traefik
      - --docker.watch
      - --web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.docker.network=proxy-traefik-network"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:${env_domain_prefix}logging-proxy.joericearchitect.com"
        - "jra.environment-flip=blue"
        - "jra.application-name=jarch-infra-logging-proxy-traefik"
        - "jra.container-name=jarch-infra-logging-proxy-traefik"
        - "jra.domain-name=${env_domain_prefix}logging-proxy.joericearchitect.com"

 
networks:
    proxy-traefik-network:
 